training_mode: 'crossvalidate' #'full': no test data, utilize the full testsuite; "cv" for cross-validation
data_dir: data/
results_dir: data/results/
experiment_name: bidirectional_lstm
combined_dataset_filename: 'dataset_combined.json'
interpolated_road_points_size: 197
data_folder_name: executed-10000
k_fold: 5
parameters:
  lstm_cells: 220
  learning_rate: 0.001
  batch_size: 128
  epochs: 2
